# Site settings
title: yankeyhotel | The misplaced portfolio of an eccentric developer.
email: yankeyhotel@gmail.com
description: "The misplaced portfolio of an eccentric developer."
baseurl: ""
url: "http://yankeyhotel.com"

# Build settings
markdown: kramdown
permalink: pretty
